### ISSUE TITLE
Application error in blog page

### ISSUE THREAD

**Issue by clicktodev** [kentcdodds/kentcdodds.com#473]
To reporduce:

1. go to [blog page](https://kentcdodds.com/blog)
2. Open **useEffect vs useLayoutEffect** [article](https://kentcdodds.com/blog/useeffect-vs-uselayouteffect)
3. scroll down and open visit course [link](https://epicreact.dev/)
4. go back in browser history very quickly (click twice quickly on the go back button)
5. you should find yourself in the blog page
6. instead error appears

This doesn't always happen, I think it only happens when the **useEffect vs useLayoutEffect** article is featured

```
TypeError: Cannot read properties of undefined (reading 'links')
    at https://kentcdodds.com/build/_shared/chunk-NA3JZD7E.js:9:330
    at Array.map (<anonymous>)
    at _n (https://kentcdodds.com/build/_shared/chunk-NA3JZD7E.js:9:284)
    at https://kentcdodds.com/build/_shared/chunk-NA3JZD7E.js:14:2535
    at Object.useMemo (https://kentcdodds.com/build/_shared/chunk-Y6UZ2JHA.js:6:25719)
    at r.useMemo (https://kentcdodds.com/build/_shared/chunk-52ROR7N5.js:1:6137)
    at Qo (https://kentcdodds.com/build/_shared/chunk-NA3JZD7E.js:14:2523)
    at du (https://kentcdodds.com/build/_shared/chunk-Y6UZ2JHA.js:6:19466)
    at Ba (https://kentcdodds.com/build/_shared/chunk-Y6UZ2JHA.js:8:43659)
    at Ua (https://kentcdodds.com/build/_shared/chunk-Y6UZ2JHA.js:8:39459)
```

6 total relevant errors appear in the console
![image](https://github.com/kentcdodds/kentcdodds.com/assets/34947993/90f2670a-ac45-4b47-93ea-a1ef4435efce)
![image](https://github.com/kentcdodds/kentcdodds.com/assets/34947993/21049367-5e92-4b6c-9b45-5367020b08b7)

**Comment by kentcdodds** [comment]
Nice find. This appears to be a Remix bug. I'll report it to them.

**Comment by kentcdodds** [comment]
Posted: https://github.com/remix-run/remix/issues/7080
