### ISSUE TITLE
Fix the "not wrapped in act(...)" warning blog post errors in console

### ISSUE THREAD

**Issue by anastasialanz** [kentcdodds/kentcdodds.com#525]
When I go to https://kentcdodds.com/blog/fix-the-not-wrapped-in-act-warning, I'm seeing 4 errors in the browser console for this TypeError:
```
4162-3aa2ff0c3f959eb2.js:1 TypeError: Cannot read properties of undefined (reading 'playbackRate')
    at playbackRate (1818-c47fc9c73976bf66.js:1:154063)
    at 2722-f19a1d23b867132e.js:22:39167
    at Array.reduce (<anonymous>)
    at A (2722-f19a1d23b867132e.js:22:38958)
    at t (2722-f19a1d23b867132e.js:22:2825)
    at t.resolveTransition (2722-f19a1d23b867132e.js:9:20000)
    at t.getInitialState (2722-f19a1d23b867132e.js:9:23497)
    at t.get (2722-f19a1d23b867132e.js:9:23829)
    at 2722-f19a1d23b867132e.js:22:17335
    at i (2722-f19a1d23b867132e.js:22:31369)
window.console.error @ 4162-3aa2ff0c3f959eb2.js:1Understand this errorAI
```

**Comment by kentcdodds** [comment]
A fix for this is being deployed on egghead's side. Thanks for the report!

**Comment by anastasialanz** [comment]
It's all fixed now!
